/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dale' at '16. 10. 6 오후 10:40' with Gradle 3.1
 *
 * @author Dale, @date 16. 10. 6 오후 10:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
